In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv("Salary_Data.csv")
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [3]:
s=[[23,54,64],[66,77,88]]

In [4]:
df1=pd.DataFrame(s)
df1

0   1   2
0  23  54  64
1  66  77  88

In [5]:
df2=pd.DataFrame(s,index=['Ramesh','Sresh'])
df2

0   1   2
Ramesh  23  54  64
Sresh   66  77  88

In [6]:
df3=pd.DataFrame(s,index=['Ramesh','Sresh'],columns=['maths','physics','chemistry'])
df3

maths  physics  chemistry
Ramesh     23       54         64
Sresh      66       77         88

In [7]:
s=[[23,54,64],[66,77,88]]
d={'Hari':[55,97,67],'Krishna':[99,66,76]}

In [8]:
df4=pd.DataFrame(d)
df4

Hari  Krishna
0    55       99
1    97       66
2    67       76

In [9]:
df4.iloc[1][0]

97

In [10]:
df

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [11]:
df
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values


In [12]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [13]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [14]:
x.ndim

2

In [15]:
y.ndim

1

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [23]:
reg = LinearRegression()

In [24]:
reg.fit(x_train,y_train)

LinearRegression()

In [25]:
pred = reg.predict(x_test)
pred

array([75074.50510972, 91873.8056381 , 62008.38247653, 81607.56642631,
       67608.14931932, 89073.92221671])

In [ ]:
y_test